views:
  v1/pods:
    sortColumn: AGE:desc
    columns:
      - AGE
      - NAME
      - READY
      - STATUS
      - RESTARTS
      - CPU
      - MEM
      - CPU/R:L
      - MEM/R:L
      - IP
      - NODE
