#format = "$all"
format = """
$directory\
$git_branch\
$git_status\
$git_state\
$line_break\
$pythong\
$battery\
$aws\
$kubernetes\
$character\
"""

right_format = ''

continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

[line_break]
disabled = false

[directory]
truncation_length = 2
truncate_to_repo = true

[aws]
format = '[($profile)(\($region\))]($style)'
style = "bold yellow"
disabled = false
expiration_symbol = "X"
force_display = false

[aws.region_aliases]
us-west-2 = ""

[aws.profile_aliases]
firedex-dev = ""
firedex-staging = "S"
firedex-prod = "P"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
disabled = false
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 15
style = 'bold red'

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
# format = " "
# success_symbol = " "
# error_symbol = " "
# vimcmd_symbol = ""
# vimcmd_visual_symbol = ""
# vimcmd_replace_symbol = ""
# vimcmd_replace_one_symbol = ""
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red"
stashed = '\$'
ahead = "⇡"
behind = "⇣"
up_to_date = ""
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"
typechanged = ""
ignore_submodules = false
disabled = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bright-black"
truncation_length = 9223372036854775807
truncation_symbol = "…"
only_attached = false
always_show_remote = false
ignore_branches = []
disabled = false

[git_metrics]
added_style = "green"
deleted_style = "red"
only_nonzero_diffs = true
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false
ignore_submodules = false

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[kubernetes]
symbol = ""
format = '[$symbol$context(\($namespace\))]($style)'
style = "cyan bold"
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []

[[kubernetes.contexts]]
context_pattern = "PROD"
context_alias = "Prod"
style = "blink bright-red"

[[kubernetes.contexts]]
context_pattern = "dev"
context_alias = ""
style = "dimmed cyan"

[[kubernetes.contexts]]
context_pattern = "stage"
context_alias = "Stage"
style = "dimmed red"


[python]
disabled = false
